### ISSUE TITLE
Install fails on Windows because lang.rkt is a symbol link.

### ISSUE THREAD

**Issue by yjqww6** [jsmaniac/type-expander#11]
The error message is:

copy-directory/files: encountered path that is neither file nor directory
  path: C:\Users\Administrator\AppData\Local\Temp\14939672411493967241680-jsmani
ac_type-expander_git_master\lang.rkt

**Comment by SuzanneSoy** [comment]
@yjqww6 Thanks a lot for the report!

I wrote a fix which should be available in about 15 to 20 minutes (I will close the issue once it's published).

**Comment by SuzanneSoy** [comment]
Fix deployed. Thanks again and sorry for the inconvenience.
